In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
!pip install tensorflow

In [5]:
import tensorflow as tf
print(tf.__version__)

C:\Users\munna\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


2.20.0


In [6]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [10]:
model = Sequential()

# this is our i/p layer with 2 nodes in hidden layer
model.add(Dense(2,activation='linear', input_dim=2))

# this is our o/p layer with 1 node
model.add(Dense(1,activation='linear'))

In [11]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.get_weights()

[array([[ 1.0450007 , -0.19985843],
        [-0.12009192,  1.2063574 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.4602443],
        [-0.9069024]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
# As keras initializes weights randomly 
# so we initialize our own weights with 0.1 and biases with 0

new_weights = [
    np.array([[0.1, 0.1],
        [0.1, 0.1]], dtype=np.float32),
    np.array([0., 0.], dtype=np.float32),
    np.array([[0.1], [0.1]], dtype=np.float32),
    np.array([0.], dtype=np.float32)
              ]

In [17]:
model.set_weights(new_weights)

In [18]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [20]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1) 

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 27.8873
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 27.5954
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 27.2545
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 26.8986
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26.5686
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26.1946
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 25.8552
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 25.4341 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 25.0841
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 24.6400
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24.2281
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.8382 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.3774 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.9483 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.4743
Epoch 16/75
4/4 ━━━

In [22]:
model.get_weights()

# so these are the new weights that keras change in our previous weights

[array([[0.37370932, 0.37370932],
        [0.36561784, 0.36561784]], dtype=float32),
 array([0.27234194, 0.27234194], dtype=float32),
 array([[0.3729521],
        [0.3729521]], dtype=float32),
 array([0.20475419], dtype=float32)]